// winSpecialFolder.cpp : 定義主控台應用程式的進入點。
//

#include "stdafx.h"
#include <windows.h>
#include <iostream>
#include <set>
#include <string>
#include <shlobj.h>

#pragma comment(lib, "shell32.lib")



using namespace std;

#if UNICODE
    #define tout wcout
#else
    #define tout cout
#endif 

void printCLSID(DWORD clsid, TCHAR* msg){
    TCHAR folder[MAX_PATH];
     
    SHGetSpecialFolderPath(NULL, folder, clsid, FALSE);
    tout << msg << _T(": ") << folder << endl;    
}

int _tmain(int argc, _TCHAR* argv[]){
    printCLSID(CSIDL_ADMINTOOLS, _T("CSIDL_ADMINTOOLS"));    
    printCLSID(CSIDL_ALTSTARTUP,_T("CSIDL_ALTSTARTUP"));
    printCLSID(CSIDL_APPDATA,_T("CSIDL_APPDATA"));
    printCLSID(CSIDL_BITBUCKET,_T("CSIDL_BITBUCKET"));
    printCLSID(CSIDL_CDBURN_AREA,_T("CSIDL_CDBURN_AREA"));
    printCLSID(CSIDL_COMMON_ADMINTOOLS,_T("CSIDL_COMMON_ADMINTOOLS"));
    printCLSID(CSIDL_COMMON_ALTSTARTUP,_T("CSIDL_COMMON_ALTSTARTUP"));
    printCLSID(CSIDL_COMMON_APPDATA,_T("CSIDL_COMMON_APPDATA"));
        printCLSID(CSIDL_COMMON_DESKTOPDIRECTORY, _T("CSIDL_COMMON_DESKTOPDIRECTORY"));
    printCLSID(CSIDL_COMMON_DOCUMENTS, _T("CSIDL_COMMON_DOCUMENTS"));
    printCLSID(CSIDL_COMMON_FAVORITES, _T("CSIDL_COMMON_FAVORITES"));
    printCLSID(CSIDL_COMMON_MUSIC, _T("CSIDL_COMMON_MUSIC"));
    printCLSID(CSIDL_COMMON_OEM_LINKS, _T("CSIDL_COMMON_OEM_LINKS"));
    printCLSID(CSIDL_COMMON_PICTURES, _T("CSIDL_COMMON_PICTURES"));
    printCLSID(CSIDL_COMMON_PROGRAMS, _T("CSIDL_COMMON_PROGRAMS"));
    printCLSID(CSIDL_COMMON_STARTMENU, _T("CSIDL_COMMON_STARTMENU"));
    printCLSID(CSIDL_COMMON_STARTUP, _T("CSIDL_COMMON_STARTUP"));
    printCLSID(CSIDL_COMMON_TEMPLATES, _T("CSIDL_COMMON_TEMPLATES"));
    printCLSID(CSIDL_COMMON_VIDEO, _T("CSIDL_COMMON_VIDEO"));
    printCLSID(CSIDL_COMPUTERSNEARME, _T("CSIDL_COMPUTERSNEARME"));
    printCLSID(CSIDL_CONNECTIONS, _T("CSIDL_CONNECTIONS"));
    printCLSID(CSIDL_CONTROLS, _T("CSIDL_CONTROLS"));
    printCLSID(CSIDL_COOKIES, _T("CSIDL_COOKIES"));
    printCLSID(CSIDL_DESKTOP, _T("CSIDL_DESKTOP"));
    printCLSID(CSIDL_DESKTOPDIRECTORY, _T("CSIDL_DESKTOPDIRECTORY"));
    printCLSID(CSIDL_DRIVES, _T("CSIDL_DRIVES"));
    printCLSID(CSIDL_FAVORITES, _T("CSIDL_FAVORITES"));
    printCLSID(CSIDL_FONTS, _T("CSIDL_FONTS"));
    printCLSID(CSIDL_HISTORY, _T("CSIDL_HISTORY"));
    printCLSID(CSIDL_INTERNET, _T("CSIDL_INTERNET"));
    printCLSID(CSIDL_INTERNET_CACHE, _T("CSIDL_INTERNET_CACHE"));
    printCLSID(CSIDL_LOCAL_APPDATA, _T("CSIDL_LOCAL_APPDATA"));
    printCLSID(CSIDL_MYDOCUMENTS, _T("CSIDL_MYDOCUMENTS"));
    printCLSID(CSIDL_MYMUSIC, _T("CSIDL_MYMUSIC"));
    printCLSID(CSIDL_MYPICTURES, _T("CSIDL_MYPICTURES"));
    printCLSID(CSIDL_MYVIDEO, _T("CSIDL_MYVIDEO"));
    printCLSID(CSIDL_NETHOOD, _T("CSIDL_NETHOOD"));
    printCLSID(CSIDL_NETWORK, _T("CSIDL_NETWORK"));
    printCLSID(CSIDL_PERSONAL, _T("CSIDL_PERSONAL"));
    printCLSID(CSIDL_PRINTERS, _T("CSIDL_PRINTERS"));
    printCLSID(CSIDL_PRINTHOOD, _T("CSIDL_PRINTHOOD"));
    printCLSID(CSIDL_PROFILE, _T("CSIDL_PROFILE"));
    printCLSID(CSIDL_PROGRAM_FILES, _T("CSIDL_PROGRAM_FILES"));
    printCLSID(CSIDL_PROGRAM_FILESX86, _T("CSIDL_PROGRAM_FILESX86"));
    printCLSID(CSIDL_PROGRAM_FILES_COMMON, _T("CSIDL_PROGRAM_FILES_COMMON"));
    printCLSID(CSIDL_PROGRAM_FILES_COMMONX86, _T("CSIDL_PROGRAM_FILES_COMMONX86"));
    printCLSID(CSIDL_PROGRAMS, _T("CSIDL_PROGRAMS"));
    printCLSID(CSIDL_RECENT, _T("CSIDL_RECENT"));
    printCLSID(CSIDL_RESOURCES, _T("CSIDL_RESOURCES"));
    printCLSID(CSIDL_RESOURCES_LOCALIZED, _T("CSIDL_RESOURCES_LOCALIZED"));
    printCLSID(CSIDL_SENDTO, _T("CSIDL_SENDTO"));
    printCLSID(CSIDL_STARTMENU, _T("CSIDL_STARTMENU"));
    printCLSID(CSIDL_STARTUP, _T("CSIDL_STARTUP"));
    printCLSID(CSIDL_SYSTEM, _T("CSIDL_SYSTEM"));
    printCLSID(CSIDL_SYSTEMX86, _T("CSIDL_SYSTEMX86"));
    printCLSID(CSIDL_TEMPLATES, _T("CSIDL_TEMPLATES"));
    printCLSID(CSIDL_WINDOWS, _T("CSIDL_WINDOWS"));
    printCLSID(CSIDL_FLAG_CREATE, _T("CSIDL_FLAG_CREATE"));
    printCLSID(CSIDL_FLAG_DONT_UNEXPAND, _T("CSIDL_FLAG_DONT_UNEXPAND"));
    printCLSID(CSIDL_FLAG_DONT_VERIFY, _T("CSIDL_FLAG_DONT_VERIFY"));
    printCLSID(CSIDL_FLAG_NO_ALIAS, _T("CSIDL_FLAG_NO_ALIAS"));
    printCLSID(CSIDL_FLAG_PER_USER_INIT, _T("CSIDL_FLAG_PER_USER_INIT")); 
    printCLSID(CSIDL_FLAG_MASK, _T("CSIDL_FLAG_MASK")); 

    
	return 0;
}

